// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

// This process will use the same config that `yarn test` is using
module.exports = {
  ...standard.jestConfig(),
  moduleNameMapper: {
    '^@src(/.*)': '<rootDir>/src$1',
    '^@app(/.*)': '<rootDir>/src/app$1',
    '^@domain(/.*)': '<rootDir>/src/domain$1',
    '^@test(/.*)': '<rootDir>/test$1',
  },
};
