# This is a basic workflow that is manually triggered

name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Tagger
        # You may pin to the exact commit or the version.
        # uses: Actions-R-Us/actions-tagger@95c51c646e75db5c6b7d447e3087bcee58677341
        uses: Actions-R-Us/actions-tagger@v2.0.1
      - name: Create Release
        # You may pin to the exact commit or the version.
        # uses: ncipollo/release-action@1df3b9d90da563e0a6f5e19f350774bc1074df54
        uses: ncipollo/release-action@v1.7.2
        with:
          artifacts: dist
          artifactContentType: "application/zip" 
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}

